### ISSUE TITLE
redis key appended with timestamp and there is a time delay!

### ISSUE THREAD

**Issue by ctippur** [fluent-plugins-nursery/fluent-plugin-redis#2]
Hello,

fluent-plugin-redis - looks like adds a index by default. Is there any way to override it so that it does not do that?

For example, 

Here are some of the keys stored:

user_pref.foo.1433835158.1

Is there a way to just store user_pref.foo (I want a insert or update functionality)?

Also, I see that there is a time delay in storing the message in fluentd. I am not sure why. Sometimes it takes upto a min to load the new data.
- Shekar

**Comment by cosmo0920** [comment]
> Is there a way to just store user_pref.foo (I want a insert or update functionality)?

Currently, it is impossible.
After using v0.14 API will be able to configure this.
But update functionality seems to be dangerous.

> Also, I see that there is a time delay in storing the message in fluentd. I am not sure why. Sometimes it takes upto a min to load the new data.

This is BufferedOutput plugin.
This kind of plugins flushes its buffer every 60 seconds by default.
It is expected behavior.

**Comment by cosmo0920** [comment]
> Also, I see that there is a time delay in storing the message in fluentd. I am not sure why. Sometimes it takes upto a min to load the new data.

If you want to flush in short time, please specify `flush_interval 5s` like value in Fluentd conf.
